# CI de Nível 01 - Disparo Manual através de clique

# A pipeline só será executada quando disparada manualmente pela UI
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

stages:
  - test

e2e-tests:
  stage: test
  image: node:24
  script:
    - npm install -g yarn
    - yarn install
    - yarn playwright install --with-deps
    - yarn run e2e