workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

stages:
  - test

e2e-tests:
  stage: test
  image: node:24
  script:
    - command -v yarn || npm install -g yarn   
    - yarn install
    - yarn playwright install --with-deps
    - yarn run e2e